### ISSUE TITLE
Warning: Illegal string offset 'admin'

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#2732]
Just checkout to latest 2.4.x-dev version of sonata-admin-bundle and got this error:

```
An exception has been thrown during the rendering of a template ("Warning: Illegal string offset 'admin'") in SonataAdminBundle:Core:dashboard.html.twig at line 88.
```

Here, my sonata configuration file. As you can see, I deactivate all the overrides without any success.

```yaml
# SonataBlock Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]

# SonataAdmin Configuration
sonata_admin:
    title: Administration
#    templates:
#        layout:               admin/standard_layout.html.twig
#        user_block:           admin/CORE/user_block.html.twig
#        search_result_block:  admin/Block/block_search_result.html.twig

#sonata_doctrine_orm_admin:
#    templates:
#        types:
#            list:
#                user:       admin/CRUD/list_user.html.twig
#                partner:    admin/CRUD/list_partner.html.twig
#                raw:        admin/CRUD/list_raw.html.twig
#            show:
#                user:       admin/CRUD/show_user.html.twig
#                partner:    admin/CRUD/show_partner.html.twig
#                raw:        admin/CRUD/show_raw.html.twig
```

Installed sonata's packages:

```bash
$ composer -i info | grep sonata
sonata-project/admin-bundle              dev-ddn 28597e8                   Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.13                            Symfony SonataBlockBundle
sonata-project/cache                     1.0.4                             Cache library
sonata-project/core-bundle               dev-master 87a84ae                Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle dev-list-builder-template 08c7715 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.9                             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.3.4                             Lightweight Exporter library
sonata-project/intl-bundle               2.2.1                             Symfony SonataIntlBundle
```
Note: `dev-ddn` branch was just synchronized from your master branch as you can see [here](https://github.com/Soullivaneuh/SonataAdminBundle/commits/ddn).

Please tell me if you need more information to solve this issue.

Thanks.

**Comment by syeo66** [comment]
I just noticed the same thing

**Comment by Atko** [comment]
Same here.

**Comment by scasei** [comment]
following feature is buggy:
https://github.com/sonata-project/SonataAdminBundle/commit/daadcf2d680607f2c0615a13357e01754dada395

it is a bc break, this user should provide a bc fix or update documentation

**Comment by Soullivaneuh** [comment]
So @scasei, what should I change in my configuration?

Thanks.

**Comment by rande** [comment]
@Soullivaneuh no, we need to fix this issue.

**Comment by Soullivaneuh** [comment]
Ok, waiting for this fix so, thanks!

**Comment by rande** [comment]
should be fixed. post a comment if not ;)

**Comment by Soullivaneuh** [comment]
@rande I'm sorry but this is apparently not fixed for me, same error:

```
An exception has been thrown during the rendering of a template ("Warning: Illegal string offset 'admin'") in SonataAdminBundle:Core:dashboard.html.twig at line 88.
```

Here my fresh sonata package installation:
```sh
$ composer -i info | grep sonata
sonata-project/admin-bundle              dev-master 74d2fef Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.13             Symfony SonataBlockBundle
sonata-project/cache                     1.0.4              Cache library
sonata-project/core-bundle               dev-master 87a84ae Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 2.3.1              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.9              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.3.4              Lightweight Exporter library
sonata-project/intl-bundle               2.2.1              Symfony SonataIntlBundle
```

I'm trying to investigate why this not works again...

**Comment by fredericaebi** [comment]
I have still the same problem as Soullivaneuh.

By the way, it's not the first time that we make an update of sonata admin run into some painful regression bug.

**Comment by Soullivaneuh** [comment]
@fredericaebi to take defense of sonata admin's developers, it's a dev-master version, this is not stable.

As now, I can find where is the issue. Where is the code fault @rande ? If I can help a little... ;)

**Comment by aitboudad** [comment]
fixed in #2739

**Comment by featuriz** [comment]
Issue not fixed yet. In SonataAdminBundle3.x same error.

> An exception has been thrown during the rendering of a template ("Error while sending HTTP request") in SonataAdminBundle:Core:dashboard.html.twig at line 88. 

I'm using HWIOAuthBundle and SonataAdminBundle-3.x

I have 4 roles ROLE_FZ, ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER

This error occurs only at backend. If a user logged in by oauth(facebook,twiiter), in the debug_toolbar the user name occus. I can't access /admin/dashboard but i can access /home /contact etc (frontend).

hwi_oauth:
    firewall_names: [main]
#    connect:
#        account_connector:      hwi_oauth.user.provider.entity
    resource_owners:
        facebook:
            type:                facebook
            client_id:           %facebook_app_id%
            client_secret:       %facebook_app_secret%
            scope:              "email"
            options:
                csrf:           true
                display:        popup
        google:
            type:               google
            client_id:          %google_app_id%
            client_secret:      %google_app_secret%
            scope:              "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            paths:
                email:          "email"
            options:
                csrf:           true
        twitter:
            type:               twitter
            client_id:          %twitter_app_id%
            client_secret:      %twitter_app_secret%
            scope:              "email"
            options:
                csrf:           true

app_login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }
    
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
    
facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

twitter_login:
    path: /login/check-twitter

> Same thing works in older SonataAdmin Bundle. I just copy paste to 3.x

I hope someone can help me

**Comment by greg0ire** [comment]
# The initial error

> An exception has been thrown during the rendering of a template ("Warning: Illegal string offset 'admin'") in SonataAdminBundle:Core:dashboard.html.twig at line 88.


# Your error

> Issue not fixed yet. In SonataAdminBundle3.x same error.
>   An exception has been thrown during the rendering of a template ("Error while sending HTTP request") in SonataAdminBundle:Core:dashboard.html.twig at line 88.

Do yo not see the difference? This isn't the same error at all… you should file a new issue, and if you do, make sure to provide a stack trace.
