### ISSUE TITLE
URGENT - FatalErrorException in Admin.php line 48

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2797]
After my recent composer update to `dev-master` I get:
**FatalErrorException in Admin.php line 48: Compile Error: Declaration of Sonata\AdminBundle\Admin\Admin::validate() must be compatible with Sonata\AdminBundle\Admin\AdminInterface::validate(Sonata\CoreBundle\Validator\ErrorElement $errorElement, $object)**

Any help?

**Comment by rande** [comment]
The issue is fixed

**Comment by webdevilopers** [comment]
Thanks! That was the shortest living issue ever. :)

**Comment by webdevilopers** [comment]
@rande Can you give me a short hint how to force Composer use the current commit?

It still uses the old one not the 325b7b91c2
```
Updating dependencies (including require-dev)
  - Installing sonata-project/admin-bundle (dev-master 325b7b9)
```

**Comment by webdevilopers** [comment]
I removed my `vendors` `sonata-project` folder, my `composer cache`, installed `2.3.1.` and switched back to:
`"sonata-project/admin-bundle": "dev-master"`.

But still composer is not installing the latest commit you merged @rande to fix this issue. :(

**Comment by webdevilopers** [comment]
I now tried
```"sonata-project/admin-bundle": "@dev"```
but that will give me a similar error:
**PHP Fatal error:  Declaration of Sonata\MediaBundle\Block\GalleryBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /.../vendor/sonata-project/media-bundle/Block/GalleryBlockService.php on line 248**

**Comment by rande** [comment]
we are migrating some lib to CoreBundle. Please we do know there is something broken, just use stable version or please be patient

**Comment by webdevilopers** [comment]
Good to know. I see the admin commit now works. Any schedule when the migration will be done?
I will wait then...

**Comment by rande** [comment]
This should be fixed

**Comment by webdevilopers** [comment]
I still get a
**PHP Fatal error:  Declaration of Sonata\MediaBundle\Block\GalleryBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /home/mborchers/NetBeansProjects/sf2/vendor/sonata-project/media-bundle/Block/GalleryBlockService.php on line 248**

I'm using:
```"sonata-project/media-bundle": "2.3.*"```

Should I use `dev-master` by now? Because that give me:
**symfony/framework-standard-edition 2.5.x-dev requires sonata-project/media-bundle dev-master -> no matching package found.**

**Comment by webdevilopers** [comment]
I finally managed to get the `dev-master`. But I had to include the `ClassificationBundle` too.
Now I'm stucked with an older issue I had before:
- https://github.com/sonata-project/SonataMediaBundle/issues/570
- https://github.com/sonata-project/SonataClassificationBundle/issues/47
