### ISSUE TITLE
$this->getSubject() on embedded admins is not working like the documentation describes

### ISSUE THREAD

**Issue by remoteclient** [sonata-project/SonataAdminBundle#2879]
For my project i develop an image gallery module. My gallery class embeds the galleryFile class via sonata_type_collection:

```php
class GalleryAdmin ...
    ->add('files', 'sonata_type_collection', array(
                        'by_reference' => false,
                        'cascade_validation' => true,
                    ), array(
                        'edit' => 'inline',
                        'inline' => 'table',
                        'sortable'  => 'position'
                    ))
```
In the galleryFileAdmin I try to determine if the admin class is embedded or not like the documentation suggests to generate the filepath.

```php
class GalleryFileAdmin ...

private function generateFilePreview($subject)
    {
        $container = $this->getConfigurationPool()->getContainer();
        $fileUrl = $container->get('request')->getBasePath().'/'.$subject->getAssetsFolder().$subject->getFilename();
        $help = '';
        if (($subject = $this->getSubject()) && $subject->getFilename())
        {
            $help = '<img style="max-width: 120px; height: auto;" src="'.$fileUrl.'" alt="" />';
        }
        
        return $help;
    }

protected function configureFormFields(FormMapper $formMapper)
    {
        if($this->hasParentFieldDescription())
        { // this Admin is embedded
            // $getter will be something like 'getlogoImage'
            $getter = 'get' . $this->getParentFieldDescription()
                                   ->getFieldName();
            // get hold of the parent object
            $parent = $this->getParentFieldDescription()
                           ->getAdmin()
                           ->getSubject();
            if ($parent)
            {
                $subject = $parent->$getter();
            } else
            {
                $subject = null;
            }
        } else
        {
            $subject = $this->getSubject();
        }
        ....
       ->add('file', 'file', array(
                'required' => false,
                'label' => 'Image',
                'help' => $this->generateFilePreview($subject)
            )) 
        ....

}
```
The code from the documentation returns a PersistentCollection instead of a subject.
Error:
Attempted to call method "getAssetsFolder" on class "Doctrine\ORM\PersistentCollection".

I have found some related issues here but none of them comes to a solution so i write this to push this issue.

possible related issues are:

[#991](https://github.com/sonata-project/SonataAdminBundle/issues/991)
[#1568](https://github.com/sonata-project/SonataAdminBundle/issues/1568)
[#2076](https://github.com/sonata-project/SonataAdminBundle/pull/2076)

**Comment by rande** [comment]
This commit should fix the issue: https://github.com/sonata-project/SonataAdminBundle/commit/1a5ba565a75c6c43867c52210cb78ec29a2b6748

**Comment by remoteclient** [comment]
@rande Thank you for looking into this. Sadly the commit doesn't solve my problem. The exception still appears. Am I doing something wrong referring to the code above?

I tried using the code above and get: Attempted to call method "getAssetsFolder" on class "Doctrine\ORM\PersistentCollection".

I also tried $subject = $this->getSubject;    With this the help field is empty.

**Comment by Nexotap** [comment]
I have a line like this in composer:

        "sonata-project/admin-bundle": "2.3.*"

I cant see this fix in the code. Do I have to get a dev version for this fix?

**Comment by nrodriguez-tupaca** [comment]
[https://github.com/sonata-project/SonataAdminBundle/commit/1a5ba565a75c6c43867c52210cb78ec29a2b6748](url) fixes the issue, however I have the same question than Nexotap: how should I add this to my 2.3.* version? 
This fix has been pulled just for 3.* versions!

**Comment by core23** [comment]
Please don't use `2.3`. We don't support this version anymore.

**Comment by OskarStark** [comment]
is this the same problem @nrodriguez-tupaca ?

#3747

**Comment by nrodriguez-tupaca** [comment]
@OskarStark I'm not sure
@core23 ok, we'll migrate to 3.* in our project. are you aware that the [installation instructions](https://sonata-project.org/bundles/admin/3-x/doc/getting_started/installation.html) in the official documentation talks about installing 2.3 ?

**Comment by core23** [comment]
Created a new PR for that (https://github.com/sonata-project/SonataAdminBundle/pull/3914). Thanks @nrodriguez-tupaca

**Comment by fsanter** [comment]
Hello,

I'm using 3.19.0 and it's still wrong (I tried 3.13.0 : the same).

I have 3 entities, or more, that have oneToOne with Image entity. (User / Company / Program), embedded with sonata_type_admin. It works for User and Company, but for Program in ImageAdmin, $this->getSubject() returns wrong object (It returns Image object that have the ID of selected Program (and if I updates the Program Image, it actually updates the Image of another entity).

I don't understand why it works for some entities and not for others :(
The code is exactly the same for all (doctrine and sonata admin).

User :
`    oneToOne:
        photo:
            targetEntity: AppBundle\Entity\Image
            cascade: ['all']`
`$formMapper
            ->add('photo', 'sonata_type_admin',
                array('delete' => false, 'btn_add' => false, 'label' => 'Photo', 'required' => false)
            )
        ;`

Program:
`    oneToOne:
        image:
            targetEntity: AppBundle\Entity\Image
            cascade: ['all']`
`        $formMapper
            ->add('photo', 'sonata_type_admin',
                array('delete' => false, 'btn_add' => false, 'label' => 'Image', 'required' => false)
            )
        ;`

Can you help me ?
Thanks

**Comment by fsanter** [comment]
I have more information : 
It works only if Image is set at creation. I choose an image and image_id is set, and after, during update, the good subject is returned, and I can update correctly.
However in my case, Image is non required, then image_id is set to null at creation. In this case, it doesn't works. During update, instead of null, image_id is set with the parent entity ID :/

For the moment, I solved the problem by always setting image_id, even if I don't select one. I allow null value for all Image properties...
In front-office, I have to check `if $image->getPath() is not null` instead of `if $image is not null`.

Thanks
