### ISSUE TITLE
Upgrading to 3.50/3.51 breaks my interface 

### ISSUE THREAD

**Issue by AnthonyBerisha** [sonata-project/SonataAdminBundle#6099]
#### Sonata packages

```
sonata-project/admin-bundle              3.51.0 3.66.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.17.0 3.18.5 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.15.0 3.18.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.2.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.5.1  1.6.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.1  3.17.1 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.11.0 2.2.0  Lightweight Exporter library


```

#### Symfony packages

```
symfony/asset                 v4.3.11 v4.3.11 Symfony Asset Component
symfony/browser-kit           v4.3.11 v4.3.11 Symfony BrowserKit Component
symfony/cache                 v4.3.11 v4.3.11 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                v4.3.11 v4.3.11 Symfony Config Component
symfony/console               v4.3.11 v4.3.11 Symfony Console Component
symfony/contracts             v1.1.8  v2.1.1  A set of abstractions extracted out of the Symfony components
symfony/css-selector          v4.3.11 v4.3.11 Symfony CssSelector Component
symfony/debug                 v4.3.11 v4.3.11 Symfony Debug Component
symfony/debug-bundle          v4.3.11 v4.3.11 Symfony DebugBundle
symfony/debug-pack            v1.0.7  v1.0.8  A debug pack for Symfony projects
symfony/dependency-injection  v4.3.11 v4.3.11 Symfony DependencyInjection Component
symfony/doctrine-bridge       v4.3.11 v4.3.11 Symfony Doctrine Bridge
symfony/dom-crawler           v4.3.11 v4.3.11 Symfony DomCrawler Component
symfony/dotenv                v4.3.11 v4.3.11 Registers environment variables from a .env file
symfony/event-dispatcher      v4.3.11 v4.3.11 Symfony EventDispatcher Component
symfony/expression-language   v4.3.11 v4.3.11 Symfony ExpressionLanguage Component
symfony/filesystem            v4.3.11 v4.3.11 Symfony Filesystem Component
symfony/finder                v4.3.11 v4.3.11 Symfony Finder Component
symfony/flex                  v1.6.2  v1.7.0  Composer plugin for Symfony
symfony/form                  v4.3.11 v4.3.11 Symfony Form Component
symfony/framework-bundle      v4.3.11 v4.3.11 Symfony FrameworkBundle
symfony/http-client           v4.4.4  v4.3.11 Symfony HttpClient component
symfony/http-foundation       v4.3.11 v4.3.11 Symfony HttpFoundation Component
symfony/http-kernel           v4.3.11 v4.3.11 Symfony HttpKernel Component
symfony/inflector             v4.3.11 v4.3.11 Symfony Inflector Component
symfony/intl                  v4.3.11 v4.3.11 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lock                  v4.3.11 v4.3.11 Symfony Lock Component
symfony/maker-bundle          v1.14.6 v1.18.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger             v4.3.11 v4.3.11 Symfony Messenger Component
symfony/mime                  v4.3.11 v4.3.11 A library to manipulate MIME messages
symfony/monolog-bridge        v4.3.11 v4.3.11 Symfony Monolog Bridge
symfony/monolog-bundle        v3.5.0  v3.5.0  Symfony MonologBundle
symfony/options-resolver      v4.3.11 v4.3.11 Symfony OptionsResolver Component
symfony/orm-pack              v1.0.8  v1.0.8  A pack for the Doctrine ORM
symfony/phpunit-bridge        v4.3.11 v5.0.8  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu     v1.14.0 v1.17.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn     v1.15.0 v1.17.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring     v1.15.0 v1.17.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72        v1.15.0 v1.17.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73        v1.15.0 v1.17.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process               v4.3.11 v4.3.11 Symfony Process Component
symfony/profiler-pack         v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access       v4.3.11 v4.3.11 Symfony PropertyAccess Component
symfony/property-info         v4.3.11 v4.3.11 Symfony Property Info Component
symfony/proxy-manager-bridge  v4.3.11 v4.3.11 Symfony ProxyManager Bridge
symfony/routing               v4.3.11 v4.3.11 Symfony Routing Component
symfony/security-acl          v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle       v4.3.11 v4.3.11 Symfony SecurityBundle
symfony/security-core         v4.3.11 v4.3.11 Symfony Security Component - Core Library
symfony/security-csrf         v4.3.11 v4.3.11 Symfony Security Component - CSRF Library
symfony/security-guard        v4.3.11 v4.3.11 Symfony Security Component - Guard
symfony/security-http         v4.3.11 v4.3.11 Symfony Security Component - HTTP Integration
symfony/serializer            v4.3.11 v4.3.11 Symfony Serializer Component
symfony/stopwatch             v4.3.11 v4.3.11 Symfony Stopwatch Component
symfony/swiftmailer-bundle    v3.4.0  v3.4.0  Symfony SwiftmailerBundle
symfony/templating            v4.3.11 v4.3.11 Symfony Templating Component
symfony/translation           v4.3.11 v4.3.11 Symfony Translation Component
symfony/twig-bridge           v4.3.11 v4.3.11 Symfony Twig Bridge
symfony/twig-bundle           v4.3.11 v4.3.11 Symfony TwigBundle
symfony/validator             v4.3.11 v4.3.11 Symfony Validator Component
symfony/var-dumper            v4.3.11 v4.3.11 Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter          v4.3.11 v4.3.11 A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link              v4.3.11 v4.3.11 Symfony WebLink Component
symfony/web-profiler-bundle   v4.3.11 v4.3.11 Symfony WebProfilerBundle
symfony/webpack-encore-bundle v1.7.3  v1.7.3  Integration with your Symfony app & Webpack Encore!
symfony/yaml                  v4.3.11 v4.3.11 Symfony Yaml Component
```

#### PHP version

```
PHP 7.2.27 (cli) (built: Feb  1 2020 21:06:44) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.8.1, Copyright (c) 2002-2019, by Derick Rethans
    with blackfire v1.34.0~linux-x64-non_zts72, https://blackfire.io, by Blackfire

```

## Subject
I am currently trying to upgrade the sonata-project/admin-bundle package from 3.36 to 3.51 and everything is fine up to the 3.50. 

## Steps to reproduce
Upgrade sonata-project/core-bundle from 3.13.7 => 3.15.0
Upgrade sonata-project/exporter from 1.9.1 => 1.11.0
Upgrade sonata-project/admin-bundle from 3.36 => 3.50/3.51

## Expected results
The sonata interface to display everything correctly.

## Actual results
The table header is broken, as well as the navigation sidebar

![image](https://user-images.githubusercontent.com/47449569/82683935-1a41e980-9c52-11ea-915f-2b62ee6959bc.png)

**Comment by VincentLanglet** [comment]
Did you tried more recent version ? This is maybe fixed in the last one.

There is not a lot of changes between 3.50 and 3.51.
https://github.com/sonata-project/SonataAdminBundle/compare/3.50.0...3.51.0

**Comment by AnthonyBerisha** [comment]
Tried upgrading to 3.66 and had to upgrade other packages as well to do so
However the problem still persists

**Comment by VincentLanglet** [comment]
> Tried upgrading to 3.66 and had to upgrade other packages as well to do so
> However the problem still persists

This seems weird. Nobody got this issue...
And I don't see why this should be 3.51 related.

From now, if you downgrade the AdminBundle, and ONLY the AdminBundle to 3.51, the problem is still here, and if you downgrade to 3.50, the problem is not here. Can you confirm ?

Did you override some templates ? or classes ?

**Comment by AnthonyBerisha** [comment]
The problem appears from the 3.50 and above.
If I downgrade to anything below 3.50 it works as expected.
We do extend templates but not classes<<<<<<

**Comment by VincentLanglet** [comment]
When you said
> I am currently trying to upgrade the sonata-project/admin-bundle package from 3.36 to 3.51 and everything is fine up to the 3.50.

I understood that 3.50 was ok and 3.51 wasn't.

> The problem appears from the 3.50 and above.
> If I downgrade to anything below 3.50 it works as expected.
> We do extend templates but not classes

But I understand now that 3.50 is not ok and 3.49.1 is ok (and we don't care about 3.51 then).

This is the changes between the two versions https://github.com/sonata-project/SonataAdminBundle/compare/3.49.1...3.50.0

You could update the version commit by commit in order to help us to find which PR introduce the issue.

**Comment by AnthonyBerisha** [comment]
Hi
Yes sorry I wasn't being clear

I updated the 3.49.1 progressively commit by commit and found out this [one](https://github.com/sonata-project/SonataAdminBundle/commit/7619f20f25fea2432784c490539557a68424cf96) breaks everything

I tried updating twig/twig but we apparently already have it in version 2.12.5 even though it's not in the composer.json

![image](https://user-images.githubusercontent.com/47449569/82887808-cfbdb700-9f48-11ea-987d-f2901b8e66f7.png)

I assume it must be in the symfony packages by default

**Comment by VincentLanglet** [comment]
I have `twig/twig: 2.12.5` too but I don't have any issue...

**Comment by wbloszyk** [comment]
@AnthonyBerisha
Hi. 
Can you check it in clean Admin - without override or additional templetes? It is look like templates are render without space char `<ahref="`, `<thclass="`. Check logo place like logo or something before.

**Comment by AnthonyBerisha** [comment]
@wbloszyk Thanks for your reply
After checking multiple times and using the logo as an example in the `standard_layout.html.twig`
The logo block has an `{% apply spaceless %}` wrapping it 
In our file overriding this template, I reimplemented the logo block the same way but without the `{% apply spaceless %}` around it and now the logo displays properly
Do you have any idea how to fix this without having to reimplement each broken block and removing the `{% apply spaceless %}` ? The Twig documentation says it should only remove whitespaces between html element, not inside of them

**Comment by VincentLanglet** [comment]
Since nobody else has the issue, it's certainly a problem with the override you made.

**Comment by wbloszyk** [comment]
You can try delete composer.lock and run `composer install`. You can try edit file in other IDE or even in notepad. Mybe some charset is diffrent.

**Comment by AnthonyBerisha** [comment]
I have tried without overriding anything just using the `standard_layout.html.twig` but the problem still persists. This is really confusing
@wbloszyk Unfortunately same situation

When debugging the `standard_layout.html.twig` and setting up a breakpoint on the `{% apply spaceless %}` line, in the `EscaperExtension::twig_escape_filter` the second argument `$string` is this : 
![image](https://user-images.githubusercontent.com/47449569/83543940-74b63200-a4fd-11ea-8ff5-e9ee6d2955eb.png)

**Comment by sakalys** [comment]
Well this is unresolved isn't it? Can anyone share what did they do to overcome the issue?

**Comment by core23** [comment]
We did not receive any PR for this issues, so it looks like this is no "big problem" that should be solved and there was no activity on this issue for a longer time.

**Comment by sakalys** [comment]
Thanks for a quick reply @core23.

I'm facing a similar issue which messed up my layout after migrating to PHP 7.4. I'm trying to resolve this by looking at various threads here, but to no avail.

**Comment by sakalys** [comment]
To anyone who is wondering, I'm facing an issue where the html and body tags are squashed with other attributes. I. e. 

```
<htmlclass="no-js">
<!-- ... -→
 <bodyclass="sonata-bc skin-black fixed">
```

There may be others...
Even the title of the page is squashed to `AdminDasboard`.

No overrides in my case...
